// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfwysiwnacrkncgmkqpa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtmd3lzaXduYWNya25jZ21rcXBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMTQ3NDUsImV4cCI6MjA1NzU5MDc0NX0.7XU3gDmX5TygTuhotIquY3IfaJvyfb9hfMswoYJ5KvM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);